apiVersion: 1

datasources:
  - name: SmartRoomDB
    type: frser-sqlite-datasource
    access: proxy
    isDefault: true
    jsonData:
      path: /home/pi/SmartRoomMonitor/smartroom.db
    editable: true
